<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test Suite Contact</description>
   <name>TS_Contact</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7b7257cf-f3db-44dc-9b82-d15f55d52d20</testSuiteGuid>
   <testCaseLink>
      <guid>e23ff869-e957-434c-aba4-25adf9824df2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Contact/TC_Contact_Gagal_1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4907a3d-39a1-474b-a7ab-256c0551f311</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3de6950b-b784-4157-a2d8-d57edfd34e3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d60f9750-901e-439a-937f-83a2afab374c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f23ded5e-2431-4d43-88a0-168d3ff37c35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Contact/TC_Contact_Gagal_2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0be2eec5-cb77-446c-a823-f11308f01b95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8e2055e-a0d0-48a9-a7bc-822bdf0808fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10ccbf44-490c-46e7-ad30-7665873f2ada</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8da17f56-3f9f-4254-80eb-aecd7cbaeac1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Contact/TC_Contact_Gagal_3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a76e63e-81ff-48bf-b3ee-238e20306b68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40ef3f49-acba-45e8-88bb-455ecf92a74c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60ab7b16-3a31-425f-9fb5-3dbddc7ee644</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b19c9138-fd2d-4ba8-9e27-e88a9dc8f56b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Contact/TC_Contact_Gagal_4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>914ad49b-d3c4-4d5f-9db0-fb97891f9e29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fdb8466-50af-49fe-b60d-5d41d6af2749</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9e4dd6c-9081-4ce1-b05c-401acc2bd0a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc4c3097-762c-46c5-af15-4a9a11e177b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Contact/TC_Contact_Sukses</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe44219f-81ea-4f80-af49-c0c7301946c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74a80a72-06ef-452d-94b7-e310dad85636</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ee23417-c310-4b11-8174-50a68ff77d9c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
