<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_SignUp</name>
   <tag></tag>
   <elementGuidId>754fff88-61ee-44bc-96a7-c8b84efca9fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de913b8a-b352-4efc-9601-215d68a6daaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>16b93254-e25a-4cb9-9724-216fcbd039fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dc4d2503-4d47-4baa-9716-7f45bf725cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign-password</value>
      <webElementGuid>ea0f37f5-28e7-450a-b241-2aaeee4a4f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-password&quot;)</value>
      <webElementGuid>9abeb883-e038-4edf-880a-c5806b4eb6a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign-password']</value>
      <webElementGuid>01d50bc0-2b76-41da-9200-8e099c1890de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInModal']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>78674754-15a8-4098-bc14-9ddc5c0b6dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>1d6232ed-975a-431b-a035-5f6abc3fe56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'sign-password']</value>
      <webElementGuid>e2733b8e-89d3-4b4c-9d37-e48605386ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
