<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test Suite Login</description>
   <name>TS_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ce9dfa70-6285-4c69-abd1-41a43364b414</testSuiteGuid>
   <testCaseLink>
      <guid>fd2b650a-b4d0-4b83-91c6-a06b53d96bd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Login/TC_Login_Gagal_1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a731aac1-fa0c-46d1-94c9-4f5f639154f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaf2802b-46d8-4a4c-936d-9b007d9b99cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16ae9035-6b82-41ed-a9a7-af34a6d200e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Login/TC_Login_Gagal_2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94166aa4-ad5a-4448-b0a8-b76e01863232</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>651c2486-5219-445c-aa22-5586214873e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6957153-1af5-4786-bc39-7b9887454d6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Login/TC_Login_Gagal_3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f59cb3ec-f3c9-4c0a-8b99-caae520386e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46da04e3-3b69-46e9-b81a-84a0068d76e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55096664-1f09-41d7-86bc-03b76c80f541</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Login/TC_Login_Sukses</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a9c4d52-59a8-41a3-9437-1d8517e137fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df75bd59-bc3b-409c-acf8-776fc969572d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
