<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test Suite Register</description>
   <name>TS_Register</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>41a21d52-47ac-4177-b274-3440abb1d3b0</testSuiteGuid>
   <testCaseLink>
      <guid>35c15e0c-907b-48f4-8720-90525fc844b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Register/TC_Register_Gagal_1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35022a10-de4c-43db-be40-3b62b7430303</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c31e76d-e8fc-4285-9b24-8734459255f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc03e24a-b46e-4ba5-a893-1af0b472ce73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Register/TC_Register_Gagal_2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae0f1beb-ad52-45e6-9a3d-9d33e628ed7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2dcab2c-8fa2-4331-be9f-73c225a37b4f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8c5a711-53c4-4358-988c-c2cebca318b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Register/TC_Register_Gagal_3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43f8c3df-b904-4825-8798-0d6b965c54d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e34991a-5787-4559-8e21-6ca0c121d26f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d10eac95-913e-4fa6-8e60-aafe0b0a6d07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Manual/Register/TC_Register_Sukses</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6f714b5-3f22-461c-83c2-29ad104873ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ed1d6a1-ad34-467e-a10d-aa169f94c8f0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
